import "../css/style.css"

import Bootstrap from "./bootstrap.min.js"
import ContactForm from "./contact-form"
import LoadImages from "./imagesloaded.pkgd.min.js"
import Isotope from "./isotope.pkgd.min.js"
import jQuery from "./jquery-3.5.1.min.js"
import Migrate from "./jquery-migrate-1.4.1.min.js"
import Ajax from ".jquery.ajaxchimp.min.js"
import Appear from "./jquery.appear"
import Count from "./jquery.countTo"
import Easing from "./jquery.easing.1.3"
import FitVids from "./jquery.fitvids"
import LazyLoad from "./jquery.lazyload.min.js"
import LocalScroll from "./jquery.localScroll.min.js"
import MagnificPopUps from "./jquery.magnific-popup.min.js"
import Parallax from "./jquery.parallax-1.1.3"
import ScrollTo from "./jquery.scrollTo.min.js"
import SimpleText from "./jquery.simple-text-rotator.min.js"
import Sticky from "./jquery.sticky"
import Viewport from "./jquery.viewport.mini"
import Masonry from "./masonry.pkgd.min.js"
import OwlCarousel from "./owl.carousel.min.js"
import SmoothScroll from "./SmoothScroll"
import Wow from "./wow.min.js"